### ISSUE TITLE
Facing Error in Phonon Calculations 

### ISSUE THREAD

**Issue by sajidurehman** [ml-evs/matador#97] opened 2020-08-08 20:57 UTC
Hi Matthew,
I am using matador 0.9.7 along with castep 19.11 for phonon calculations of 2D materials. But i am stuck in phonon calculations. Could you please help me in this regard.

1) Firstly, I optimized the structure with matador and saw following line “LBFGS: Geometry optimization completed successfully.” in .castep for confirmation.
2) After that, copy the .res file from completed directory for phonon calculations.
3) Then, use the following setting for .cell and .param files 
**.cell parameters**
kpoints_mp_grid 10 10 1
symmetry_generate
snap_to_symmetry
phonon_kpoint_mp_grid 5 5 1           ! q-points grid
phonon_kpoint_mp_offset 0.25 0.25 0.25 
phonon_fine_kpoint_mp_grid 15 15 1
%block species_pot
NCP
%endblock species_pot

**.param parameters**
task                          : Phonon+Efield
xc_functional            : PBE
cut_off_energy          : 500 eV
opt_strategy             : speed
max_scf_cycles          : 100
grid_scale                  : 2.0
mixing_scheme         : pulay
metals_method         : dm
fix_occupancy            : true

phonon_fine_method               : interpolate
phonon_calc_lo_to_splitting     : true
phonon_write_force_constants : true

But after executing the phonon calculations I got the following error.  Could you please guide me how to fix this error? I will be very thankful to your help.
![error](https://user-images.githubusercontent.com/33825577/89719598-77447480-d9e3-11ea-9484-ed0f67ca7d2b.png)

Looking forward to hear you.
Best Regards
Sajid

**Comment by ml-evs** [comment] 2020-08-09 16:48
Hi Sajid, this is a CASTEP error warning you that your forces are too large to do a reliable phonon calculation. This general guide might help you: www.tcm.phy.cam.ac.uk/castep/Phonons_Guide/Castep_Phononsch2.html

General suggestions: 

- Use a lower `geom_force_tol=0.01` or `0.001` in your param file. 
- Turn on checkpointing and continuation so that the CASTEP phonon calculation restarts from the finished geometry optimisation (`write_checkpoint: ALL` and `continuation: default`) in your param file.
- If you use `task: phonon` rather than `phonon+Efield` then you can use `run3` to do run workflow and automate the full phonon calculation for you (as per the matador [phonon tutorial](https://docs.matador.science/en/latest/tutorials/run3_phonon.html)). I've never used `Efield` so can't help there, if that's something you need specifically, but if you have already performed a full phonon calculation then you can do the `Efield` as a continuation run.

Closing this as its not strictly a matador problem.

**Closed by ml-evs** 2020-08-09 16:48 UTC

**Comment by sajidurehman** [comment] 2020-08-11 20:09
Hi Matthew,
               Thank you so much for this great feature.  Now, matador is getting more versatile as you adding more and more features. Once again thank you delveloping this great code.

**Comment by sajidurehman** [comment] 2020-08-17 20:15
Hi Matthew,
                I tried to calculate and draw the phonon pdos along with phonon dispersion curve like provided in "**Computational Investigation of Copper Phosphides as Conversion Anodes for Lithium-Ion Batteries**". I used the following .param file for calculation. But its showing me only total DOS of phonon. 

task                          : phonon 
phonon_method                 : finitedisplacement
phonon_fine_method            : interpolate
cut_off_energy                : 300.0 eV
write_bib                     : False
xc_functional                 : LDA
geom_force_tol                : 0.05
finite_basis_corr             : 0
write_checkpoint              : none
phonon_calculate_dos          : True
pdos_calculate_weights        : True

Could you please guide me how to fix the issue. Thank you

Best Wishes
Sajid

**Comment by ml-evs** [comment] 2020-08-17 21:02
> Hi Matthew,
> I tried to calculate and draw the phonon pdos along with phonon dispersion curve like provided in "**Computational Investigation of Copper Phosphides as Conversion Anodes for Lithium-Ion Batteries**". I used the following .param file for calculation. But its showing me only total DOS of phonon.
> 
> task : phonon
> phonon_method : finitedisplacement
> phonon_fine_method : interpolate
> cut_off_energy : 300.0 eV
> write_bib : False
> xc_functional : LDA
> geom_force_tol : 0.05
> finite_basis_corr : 0
> write_checkpoint : none
> phonon_calculate_dos : True
> pdos_calculate_weights : True
> 
> Could you please guide me how to fix the issue. Thank you
> 
> Best Wishes
> Sajid

That looks fine to me, check your `.phonon_dos` file, it should always be broken down by species by CASTEP.

**Comment by sajidurehman** [comment] 2020-08-17 21:16
I noticed the last two column are only consist of zeros.  Could you please see the attached file. 
[Si.zip](https://github.com/ml-evs/matador/files/5086831/Si.zip)

 BEGIN DOS   Freq (cm-1)  g(f)   Si      
 -5000.0   0.000000   0.000000
 -4999.0   0.000000   0.000000
 -4998.0   0.000000   0.000000
 -4997.0   0.000000   0.000000

**Comment by ml-evs** [comment] 2020-08-17 21:30
If you only have silicon in the cell, then the only projector for the phonons is "Si", there's no other way to break it down

**Comment by sajidurehman** [comment] 2020-08-17 21:49
Got it. thank you so much for clarification.

**Comment by ml-evs** [comment] 2020-08-17 22:23
> Got it. thank you so much for clarification.

No problem!

**Comment by sajidurehman** [comment] 2020-08-17 22:53
Hi Matthew,
             I am trying to plot phonon graph by following statements for specially dpi option. But i am getting blank figure. Could you please guide how to fix this issue.

import numpy as np    
import matplotlib.pyplot as plt
%matplotlib inline
import matador.plotting


fig, ax = plt.subplots()

ax = matador.plotting.plot_spectral(
    'Si2', 
    phonons=True,
    band_colour='purple',
    )

plt.savefig('Si@phon.png', bbox_inches='tight', dpi=600)

**Comment by ml-evs** [comment] 2020-08-18 09:12
Hi Sajid, the problem is that `plot_spectral` will "show" the plot (`plt.show()`) by default, unless you ask to save it inside the function itself (e.g. `png=True` when you call it). To save it outside of the function, pass `show=False` to the `plot_spectral` function.

**Comment by sajidurehman** [comment] 2020-08-18 19:12
Hi Matthew,
         Thank you for reply and guidance. Now plt.savefig() properly working. But still getting blank graph along with required figure (please see the attached fig) in jupyter notebook. How to avoid this?

Moreover,  no_pdis=True option is not working in following statements.  Please also see the attached figure.

fig, ax = plt.subplots()
ax = matador.plotting.plot_spectral(
    'GaN',
    pdis_interpolation_factor=5,
    no_pids=True,
    figsize=(7, 4),
    show=False,
    plot_window=[-7.5,7.5]
)

![image](https://user-images.githubusercontent.com/33825577/90555267-8a5bff00-e1b0-11ea-9c18-53d311e49ff1.png)

**Comment by ml-evs** [comment] 2020-08-18 20:03
You also need to pass the "ax" to the plotting function, i.e. `plot_spectral(..., ax=ax, ...)` so that it knows what to draw on. In this case, you can't pass it a figsize (it will be ignored as the figure already exists). Your other option is just to not make a figure initially and let plot_spectral deal with it all (i.e. just delete your first line)

**Comment by sajidurehman** [comment] 2020-08-18 20:18
Thank you for guiding me in the right direction. what about no_pdis=true option its still not working.

**Comment by ml-evs** [comment] 2020-08-18 21:37
The options for the dispersion script are not the same as those for the plot_spectral function, what you want is `plot_pdis=False`.

https://docs.matador.science/en/stable/matador.plotting.html#matador.plotting.spectral_plotting.plot_spectral

**Comment by sajidurehman** [comment] 2020-08-19 03:38
Thnak you for right statement.

**Comment by sajidurehman** [comment] 2020-08-26 00:20
Hi Matthew,
             I have little problem regrading Phonon DOS calculation. I want to calculate the phonon dispersion and DOS by using matador like the following Fig. 
![Example](https://user-images.githubusercontent.com/33825577/91240003-30cc7500-e75a-11ea-82dd-5be6ca40a803.png)

For that purpose I used the following .cell and .param files as per my understanding (please see the attachment. After the calculation, I got the phonon dispersion (which has no imaginary part) and only total phonon DOS (which looks unstable). 
![ZnS](https://user-images.githubusercontent.com/33825577/91240080-6ec99900-e75a-11ea-92d3-c4bf687f343b.png)

I am confused if dispersion show stability why DOS shows instability and what I am missing in .cell and .param files for partial phonon DOS curves. Could you please look into my files and let me know how to fix this issue. Thank you in advance.
[ZnS.zip](https://github.com/ml-evs/matador/files/5126880/ZnS.zip)

**Comment by ml-evs** [comment] 2020-08-26 00:36
Hi @sajidurehman, I've actually just been pushing some changes to phonon PDOS etc, could you pull the master branch and see if they make a difference for you? You might have been unlucky and pulled in between some commits...

I wouldn't worry about the instability in the phonon DOS vs the dispersion, it looks to me like that DOS has a spike exactly *at* zero due to the acoustic modes at every q-point; this is a physical feature. Only modes much below 0 (say, more negative than -20 1/cm) would indicate instability, and these should also appear in the dispersion. If you use more interpolated q-points in your DOS calculation (e.g. set `phonon_fine_kpoint_mp_spacing: 0.02`) then this spike will be smaller, as in the Cu2P plot you posted from our paper.

**Comment by sajidurehman** [comment] 2020-08-26 00:58
Thank you for prompt reply. Now problem solved after pulling the master branch and again thank you for explanation.

**Comment by ml-evs** [comment] 2020-08-26 09:04
> Thank you for prompt reply. Now problem solved after pulling the master branch and again thank you for explanation.

Was a bit sleepy when I responded last night, so tweaked the wording of my answer today. The acoustic modes have zero frequency (or close) only at Γ, not at every q-point. CASTEP actually expects and corrects for this with the `phonon_sum_rule` parameter, which enforces the acoustic sum rule, see 2.3.4 of the [CASTEP phonon guide](http://www.tcm.phy.cam.ac.uk/castep/Phonons_Guide/Castep_Phononsch2.html).

**Comment by sajidurehman** [comment] 2020-08-27 03:14
Hi Matthew,
              Again thank you for more explanation. I tried the phonon_sum_rule in three different calculations with phonon_fine_kpoint_mp_spacing: 0.02 but still got the same phonon DOS graph.

1) only used 
phonon_sum_rule: True
2) Then,  
phonon_sum_rule: True 
phonon_sum_rule:_method : real-recip
3) Again then,
phonon_sum_rule: True 
phonon_sum_rule:_method : real-recip
born_charge_sum_rule: True
  
I was expecting at least some change near zero frequency (or close) only at Γ. Any further explanation would be highly appreciable. Thank you

**Comment by ml-evs** [comment] 2020-08-27 10:01
Your options 1/, 2/ and 3/ all perform the sum rule correction (which leads to the spike at 0, on by default), you might see a difference if you turned it off completely (`phonon_sum_rule_method: NONE`), but I wouldn't worry about it. The other `.param` parameter you can change is `phonon_dos_spacing`, if you make it larger, the spike at gamma will appear smaller, but the you'll get a lower fidelity DOS.

**Comment by sajidurehman** [comment] 2020-08-27 11:58
Hi Matthew,
          Thank you so much for guiding me in the right direction. After using phonon_sum_rule_method: NONE, spike move to more positive side. which looks more better to me. Again thank you.

**Comment by ml-evs** [comment] 2020-08-27 12:14
Bear in mind that you would expect phonon frequencies of 0 at gamma, as it costs no energy to translate the entire unit cell at once (which is essentially what the acoustic modes at gamma are doing, q=0 corresponds to an infinite wavelength phonon). The acoustic sum rule correction is just CASTEP's (and many other code's) way of baking that physics into the DFT simulation, so don't worry about phonons with zero frequency, just worry about those with imaginary (i.e. negative on most plots) frequencies!

**Comment by sajidurehman** [comment] 2020-08-27 12:25
Now I got it.  Again thank you for clarification.
